USE test;
DROP TABLE IF EXISTS `articles`;
CREATE TABLE IF NOT EXISTS `articles` (
    id  BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    author BIGINT(20) UNSIGNED NOT NULL,
    title VARCHAR(500) NOT NULL,
    intro_text TEXT NOT NULL,
    full_text LONGTEXT NOT NULL,
    created_at DATETIME NOT NULL,
    modifyed_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;